title: Microsoft Teams® Template Manifests
description: This repository contains manifests defining characteristics of the templates published on the SalesTim Template Store.
theme: jekyll-theme-minimal
logo: https://manifests.salestim.io/assets/salestim/logo.png
show_downloads: false